FROM alpine:latest

RUN apk add --no-cache curl bash

# Optional: Add any scripts or additional files you might need
COPY toggle-secret.sh /tasks/toggle-secret.sh

# Set a default command or entrypoint (optional)
CMD ["sh"]
