apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: toggle-secret-container
  namespace: apps
spec:
  steps:
    - name: curl-step
      image: serv-tasks:1.0.0
      script: |
        #!/bin/sh
        echo "Hello from Tekton!"
        export API_URL="http://echo-server.apps.svc.cluster.local:3000/toggle"
        /tasks/toggle-secret.sh
      # command:
      #   - /tasks/toggle-secret.sh
      # env:
      #   - name: API_URL
      #     value: "http://echo-server.apps.svc.cluster.local:3000/toggle"