apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: toggle-secret
  namespace: apps
spec:
  steps:
    - name: curl-step
      image: curlimages/curl
      script: |
        #!/bin/sh
        echo "Executing task"
        curl "http://echo-server.apps.svc.cluster.local:3000/toggle"