apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: toggle-secret
spec:
  params:
    - name: API_URL
      type: string
      description: "API endpoint to hit with the curl command"
      default: "https://example.com"
  steps:
    - name: curl-step
      image: curlimages/curl
      script: |
        #!/bin/sh
        echo "Executing task"
        curl "$(params.API_URL)"
