apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: toggle-secret-container
  namespace: tekton-pipelines
spec:
  params:
    - name: API_URL
      type: string
      description: "API endpoint to hit with the curl command"
      default: "http://echo-server.apps.svc.cluster.local:3000/toggle"
  steps:
    - name: curl-step
      image: k
      command:
        - /tasks/toggle-secret.sh
      env:
        - name: API_URL
          value: "$(params.API_URL)" 
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: "RuntimeDefault"
        capabilities:
          drop:
            - "ALL"
