apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: super-secret
  namespace: apps
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: gcpsm-secret-store-apps
  target:
    name: super-secret
    creationPolicy: Owner
  data:
  - secretKey: SVC_TASK_SECRET1
    remoteRef:
      key: SVC_TASK_SECRET1
  - secretKey: SVC_TASK_SECRET2
    remoteRef:
      key: SVC_TASK_SECRET2