name: Trigger Tekton Task

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Tekton Task
        run: |
          kubectl create taskrun --from=task/toggle-secret --name=trigger-toggle-secret-${{ github.run_id }}
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
